GET http://localhost:8080/secured/status
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGljZUBleGFtcGxlLmNvbSIsIm5iZiI6MTYwODU3MDYzMCwicm9sZXMiOltdLCJpc3MiOiJtbi1qZGJjLWF1dGgiLCJleHAiOjE2MDg1NzQyMzAsImlhdCI6MTYwODU3MDYzMH0.M6vhKnOuQGlX9sVNvwU7ifn6Vs0VuSfJNLmBck-wnjg