micronaut:
  application:
    name: mwStockBroker
  server:
    port: 8080
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: changeThisSecretInProdutionPleaseOrYouWillFall

hello:
  from:
    de: "Hallo"
    en: "Hello"

# JSON Settings
jackson:
  property-naming-strategy: SNAKE_CASE
  serialization:
    writeDatesAsTimestamps: false
    writeDatesWithZoneId: true
    wirteDateTimestampsAsNanoseconds: false
  generator:
    writeNumbersAsStrings: true
    writeBigDecimalAsPlain: true
  deserialization:
    failOnUnknownProperties: false

# Flyway config
flyway:
  datasources:
    defaut:
      enabled: true
      clean-schema: false
      url: ${PG_JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/mn-stock-broker`}
      user: ${PG_USERNAME:postgres-user}
      password: ${PG_PASSWORD:postgres-password}
      schemas: mn
      default-schema: mn

# Datasources
datasources:
  default:
    url: ${PG_JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/mn-stock-broker`}
    username: ${PG_USERNAME:postgres-user}
    password: ${PG_PASSWORD:postgres-password}
    driver-class-name: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES

# MICRONAUT DATA JPA
jpa:
  default:
    packages-to-scan:
      - "com.jocivaldias.broker.entity"
      - "com.jocivaldias.broker.repository"
    properties:
      hibernate:
        show_sql: false
